=== TianyiTimothy/xmldom/supportingTickets.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">  
	<xs:element name="tickets">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ticket" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:int" name="ID" />
							<xs:element type="xs:date" name="dateOfIssue" />
							<xs:element type="xs:string" name="subject" />
							<xs:element type="xs:int" name="userID" />
							<xs:element name="supportMessages" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:int" name="userID" />
										<xs:element type="xs:string" name="messageContent" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="status" name="status" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- status -->
	<xs:simpleType name="status">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ongoing" />
			<xs:enumeration value="resolved" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== TianyiTimothy/xmldom/supportingTickets.xml
<?xml version="1.0" encoding="utf-8" ?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="supportingTickets.xsd">
	<ticket status="resolved">
		<ID>1012223</ID>
		<dateOfIssue>2020-01-20</dateOfIssue>
		<subject>I can't submit my work!</subject>
		<userID>209221</userID>
		<supportMessages>
			<userID>209221</userID>
			<messageContent>When I click on submit at my lab page, nothing happens!</messageContent>
		</supportMessages>
		<supportMessages>
			<userID>100001</userID>
			<messageContent>This usually happens with a slow network, so you might want to check your network.</messageContent>
		</supportMessages>
		<supportMessages>
			<userID>209221</userID>
			<messageContent>Thank you!</messageContent>
		</supportMessages>
	</ticket>
	<ticket status="ongoing">
		<ID>1012224</ID>
		<dateOfIssue>2020-01-22</dateOfIssue>
		<subject>I can't submit my work again!</subject>
		<userID>209221</userID>
		<supportMessages>
			<userID>209221</userID>
			<messageContent>When I click on submit at my lab page, nothing happens! Even with fast net speed!</messageContent>
		</supportMessages>
	</ticket>
</tickets>
